- name: Installing maven package
  yum:
    name: maven
    state: installed

- name: Installing the {{component}} application.
  import_role:
    name: common
    tasks_from: Setup_App

- name:  download the dependencies & build the application
  command: mvn clean package
  args:
    chdir: /app

- name: copy the package
  copy:
    src: /app/target/shipping-1.0.jar
    dest: /app/shipping.jar
    remote_src: yes


- name: Setup SystemD & Starting {{component}} Service
  import_role:
    name: common
    tasks_from: service_start

- name: install mysql client
  yum: 
    name: mysql
    state: installed

- name: Load schema
  shell: mysql -h {{MYSQL_HOST}} -uroot -pRoboShop@1 < /app/schema/{{component}}.sql 

- name: Restart the {{component}} service.
  import_role:
    name: common
    tasks_from: restart_service
    
  
