- name: Tags example
  hosts: web
  tasks:
  - name: Installing nginx
    tags: 
    - install
    package:
      name: nginx
      state: installed
  
  - name: starting nginx
    tags: 
    - start
    service:
      name: nginx
      state: started
