- name: check application User {{USER}} existed or not
  command: id {{USER}}
  register: output
  ignore_errors: true

- name: Create a user {{USER}} if not exit
  user: 
    name: "{{USER}}"
  when: output.rc != 0

- name: Check an application directory {{app_dir}} exit or not.
  stat:
    path: "{{app_dir}}"
  register: dir
  

- name: Create a dir {{app_dir}} if not exit
  file:
    name: "{{app_dir}}"
    state: directory
  when: dir.stat.exists == False

- name: Download & Unzip the package file
  unarchive:
    src: https://roboshop-builds.s3.amazonaws.com/{{component}}.zip
    dest: "{{app_dir}}"
    remote_src: yes