- name: Installing NodeJS
  import_role:
    name: common
    tasks_from: NodeJS  

- name: Installing {{component}} application
  import_role:
    name: common
    tasks_from: Setup_App

- name: Install  the NPM dependencies
  command: npm install 
  args:
    chdir: /app

- name: startup {{component}} service
  import_role:
    name: common
    tasks_from: service_start

    